### ISSUE TITLE
Cat id varies

### ISSUE THREAD

**Issue by kostickm** [IBM/openwhisk-serverless-apis#35]
Running through the tutorial I noticed that my cat `id=1` always returned a blank result. When adding a new cat entry the `id` varied. 

I am not sure if there are clean up steps that would ensure the user is always using `id=1`, or if it should be stated that the user make note of the `id` when they do a `POST`.

**Comment by krook** [comment]
Thanks Megan. Yes, this is somewhat non-deterministic. I'll make it clear in the docs that it's not necessarily an auto increment starting from 1.
