### ISSUE TITLE
what about web actions?

### ISSUE THREAD

**Issue by sjfink** [IBM/openwhisk-serverless-apis#48]
Should we extend this example to start with "basic" web actions, and then extend it with the richer functionality of API Gateway?

Or should we alternatively create a new sample app for web actions?

**Comment by krook** [comment]
@sjfink That's a good question. I'm currently defining a next iteration of this sample, which uses Web Actions + API Gateway together. I'm on the fence as to whether we should refactor this repo, or to create a new one. 

There's also the building block version of this sample, which is at https://github.com/IBM/openwhisk-rest-api-trigger

Perhaps we update that building block repo to show Web Actions alone, then have the next iteration of this repo include both working together.

Thoughts?

**Comment by krook** [comment]
Related to #47

**Comment by krook** [comment]
Close by PR #49
